### ISSUE TITLE
After update to 11.3.0: Property 'selectNonNil' does not exist on type

### ISSUE THREAD

**Issue by jblankenhorn** [w11k/Tydux#23]
Problem

```
this.service
      .selectNonNil
```

**Comment by romanroe** [comment]
Added back in v14.0.0
